version: '3.8'

services:
  intellij-plugin:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CERTIFICATE_CHAIN=${CERTIFICATE_CHAIN}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - PRIVATE_KEY_PASSWORD=${PRIVATE_KEY_PASSWORD}
      - PUBLISH_TOKEN=${PUBLISH_TOKEN}
    # Uncomment the following line if the application exposes a port
    # ports:
    #   - "8080:8080"